# Generated by Django 3.1.7 on 2021-05-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_auto_20210503_0459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Punitions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.CharField(choices=[('1ère année', '1ère année'), ('2ème année Sciences', '2ème année Sciences'), ('2ème année Lettres', '2ème année Lettres'), ('2ème année Eco & Gestion', '2ème année Eco & Gestion'), ('2ème année Informatique', '2ème année Informatique'), ('3ème année Sciences', '3ème année Sciences'), ('3ème année Lettres', '3ème année Lettres'), ('3ème année Eco & Gestion', '3ème année Eco & Gestion'), ('3ème année Informatique', '3ème année Informatique'), ('4ème année Sciences', '4ème année Sciences'), ('4ème année Lettres', '4ème année Lettres'), ('4ème année Eco & Gestion', '4ème année Eco & Gestion'), ('4ème année Informatique', '4ème année Informatique')], default='1ère année', max_length=30)),
                ('Reason', models.CharField(max_length=30, null=True)),
                ('Decision', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='marks',
            name='Class',
            field=models.CharField(choices=[('1ère année', '1ère année'), ('2ème année Sciences', '2ème année Sciences'), ('2ème année Lettres', '2ème année Lettres'), ('2ème année Eco & Gestion', '2ème année Eco & Gestion'), ('2ème année Informatique', '2ème année Informatique'), ('3ème année Sciences', '3ème année Sciences'), ('3ème année Lettres', '3ème année Lettres'), ('3ème année Eco & Gestion', '3ème année Eco & Gestion'), ('3ème année Informatique', '3ème année Informatique'), ('4ème année Sciences', '4ème année Sciences'), ('4ème année Lettres', '4ème année Lettres'), ('4ème année Eco & Gestion', '4ème année Eco & Gestion'), ('4ème année Informatique', '4ème année Informatique')], default='1ère année', max_length=30),
        ),
        migrations.AlterField(
            model_name='studentextra',
            name='cl',
            field=models.CharField(choices=[('1ère année', '1ère année'), ('2ème année Sciences', '2ème année Sciences'), ('2ème année Lettres', '2ème année Lettres'), ('2ème année Eco & Gestion', '2ème année Eco & Gestion'), ('2ème année Informatique', '2ème année Informatique'), ('3ème année Sciences', '3ème année Sciences'), ('3ème année Lettres', '3ème année Lettres'), ('3ème année Eco & Gestion', '3ème année Eco & Gestion'), ('3ème année Informatique', '3ème année Informatique'), ('4ème année Sciences', '4ème année Sciences'), ('4ème année Lettres', '4ème année Lettres'), ('4ème année Eco & Gestion', '4ème année Eco & Gestion'), ('4ème année Informatique', '4ème année Informatique')], default='1ère année', max_length=30),
        ),
    ]
