# Generated by Django 3.1.7 on 2021-05-05 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_auto_20210504_0611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emplois',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.CharField(choices=[('1ère année', '1ère année'), ('2ème année Sciences', '2ème année Sciences'), ('2ème année Lettres', '2ème année Lettres'), ('2ème année Eco & Gestion', '2ème année Eco & Gestion'), ('2ème année Informatique', '2ème année Informatique'), ('3ème année Sciences', '3ème année Sciences'), ('3ème année Lettres', '3ème année Lettres'), ('3ème année Eco & Gestion', '3ème année Eco & Gestion'), ('3ème année Informatique', '3ème année Informatique'), ('4ème année Sciences', '4ème année Sciences'), ('4ème année Lettres', '4ème année Lettres'), ('4ème année Eco & Gestion', '4ème année Eco & Gestion'), ('4ème année Informatique', '4ème année Informatique')], default='1ère année', max_length=30)),
                ('tableau', models.FileField(max_length=30, upload_to='')),
            ],
        ),
    ]
