# Generated by Django 3.1.7 on 2021-05-05 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_emplois'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emplois',
            name='tableau',
        ),
    ]
