# Generated by Django 3.1.7 on 2021-05-07 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_remove_emplois_tableau'),
    ]

    operations = [
        migrations.AddField(
            model_name='emplois',
            name='Emp',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
