# Generated by Django 3.1.7 on 2021-05-07 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_emplois_emp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListEmplois',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Classe', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='')),
            ],
        ),
    ]
